In [113]:
pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/test/Library/Python/3.14/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/test/Library/Python/3.14/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [114]:
pip install numpy

Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (2.4.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [115]:
import numpy as np
import pandas as pd

In [116]:
df = pd.read_csv('/Users/test/Downloads/ex.csv')

In [117]:
df.isnull().sum()

Song-Name          0
Singer/Artists    10
Genre              0
Album/Movie        3
User-Rating        0
dtype: int64

In [118]:
df.dropna(inplace=True)

In [119]:
df.isnull().sum()

Song-Name         0
Singer/Artists    0
Genre             0
Album/Movie       0
User-Rating       0
dtype: int64

In [120]:
df.duplicated().sum()

np.int64(16)

In [121]:
df = df.drop_duplicates()

In [122]:
df.duplicated().sum()

np.int64(0)

In [123]:
df.shape

(2391, 5)

In [124]:
df.head()

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
0,Aankh Marey,"Kumar Sanu, Mika Singh, Neha Kakkar",BollywoodDance,Simmba,8.8/10
1,Coca Cola,"Neha Kakkar, Tony Kakkar",BollywoodDanceRomantic,Luka Chuppi,9.0/10
2,Apna Time Aayega,Ranveer Singh,BollywoodDance,Gully Boy,9.7/10
3,Mungda,"Jyotica Tangri, Shaan, Subhro Ganguly",BollywoodDance,Total Dhamaal,9.1/10
4,Tere Bin,"Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi",BollywoodRomantic,Simmba,9.2/10

In [125]:
df['User-Rating']

0       8.8/10
1       9.0/10
2       9.7/10
3       9.1/10
4       9.2/10
         ...
2415    6.2/10
2416    7.2/10
2417    7.5/10
2418    6.5/10
2419    6.6/10
Name: User-Rating, Length: 2391, dtype: object

In [126]:
l=[]
for i in df['User-Rating']:
  l.append(i[1:3])
l

['.8',
 '.0',
 '.7',
 '.1',
 '.2',
 '.1',
 '.2',
 '.5',
 '.2',
 '.6',
 '.8',
 '.4',
 '.1',
 '.2',
 '.0',
 '.7',
 '.1',
 '.0',
 '.0',
 '.1',
 '.2',
 '.2',
 '.5',
 '.6',
 '.1',
 '.0',
 '.0',
 '.2',
 '.5',
 '.4',
 '.7',
 '.3',
 '.3',
 '.5',
 '.1',
 '.0',
 '.0',
 '.1',
 '.4',
 '.4',
 '.8',
 '.2',
 '.2',
 '.6',
 '.6',
 '.0',
 '.1',
 '.5',
 '.5',
 '.5',
 '.7',
 '.9',
 '.6',
 '.5',
 '.1',
 '.7',
 '.6',
 '.3',
 '.7',
 '.9',
 '.0',
 '.0',
 '.3',
 '.3',
 '.1',
 '.0',
 '.7',
 '.2',
 '.1',
 '.0',
 '.9',
 '.5',
 '.5',
 '.7',
 '.0',
 '.1',
 '.1',
 '.5',
 '.1',
 '.6',
 '.4',
 '.0',
 '.0',
 '.6',
 '.3',
 '.0',
 '.2',
 '.3',
 '.1',
 '.6',
 '.5',
 '.5',
 '.0',
 '.4',
 '.2',
 '.6',
 '.3',
 '.7',
 '.2',
 '.3',
 '.7',
 '.0',
 '.5',
 '.4',
 '.0',
 '.2',
 '.0',
 '.4',
 '.4',
 '.1',
 '.3',
 '.2',
 '.1',
 '.0',
 '.8',
 '.9',
 '.8',
 '.9',
 '.2',
 '.7',
 '.2',
 '.4',
 '.0',
 '.9',
 '.9',
 '.7',
 '.9',
 '.6',
 '.5',
 '.7',
 '.4',
 '.5',
 '.3',
 '.3',
 '.2',
 '.3',
 '.9',
 '.7',
 '.1',
 '.6',
 '.4',
 '.6',
 '.6',
 '.1',
 '.2',
 '.6',
 '.6',
 '.8',
 '.7',
 '.4',
 '.0',
 '.1',
 '.6',
 '.3',
 '.4',
 '.2',
 '.5',
 '.6',
 '.9',
 '.4',
 '.7',
 '.4',
 '.4',
 '.5',
 '.3',
 '.1',
 '.5',
 '.4',
 '.6',
 '.4',
 '.3',
 '.1',
 '.2',
 '.0',
 '.2',
 '.7',
 '.5',
 '.7',
 '.3',
 '.3',
 '.7',
 '.0',
 '.2',
 '.2',
 '.8',
 '.1',
 '.3',
 '.2',
 '.0',
 '.2',
 '.5',
 '.6',
 '.3',
 '.7',
 '.5',
 '.9',
 '.6',
 '.7',
 '.4',
 '.2',
 '.2',
 '.1',
 '.1',
 '.7',
 '.9',
 '.4',
 '.4',
 '.0',
 '.1',
 '.4',
 '.6',
 '.3',
 '.5',
 '.5',
 '.2',
 '.6',
 '.9',
 '.6',
 '.4',
 '.4',
 '.6',
 '.6',
 '.9',
 '.6',
 '.2',
 '.7',
 '.9',
 '.7',
 '.6',
 '.2',
 '.2',
 '.2',
 '.4',
 '.0',
 '.4',
 '.7',
 '.8',
 '.6',
 '.4',
 '.9',
 '.4',
 '.0',
 '.5',
 '.5',
 '.3',
 '.7',
 '.0',
 '.2',
 '.4',
 '.1',
 '.8',
 '.1',
 '.2',
 '.2',
 '.4',
 '.0',
 '.7',
 '.4',
 '.1',
 '.8',
 '.1',
 '.1',
 '.7',
 '.7',
 '.4',
 '.5',
 '.8',
 '.9',
 '.3',
 '.5',
 '.3',
 '.2',
 '.5',
 '.9',
 '.1',
 '.3',
 '.4',
 '.3',
 '.6',
 '.8',
 '.6',
 '.1',
 '.8',
 '.8',
 '.4',
 '.4',
 '.4',
 '.1',
 '.0',
 '.5',
 '.5',
 '.3',
 '.5',
 '.9',
 '.0',
 '.6',
 '.4',
 '.5',
 '.0',
 '.5',
 '.5',
 '.8',
 '.4',
 '.3',
 '.4',
 '.1',
 '.6',
 '.7',
 '.8',
 '.1',
 '.1',
 '.1',
 '.0',
 '.3',
 '.7',
 '.2',
 '.3',
 '.3',
 '.4',
 '.0',
 '.3',
 '.9',
 '.0',
 '.4',
 '.1',
 '.4',
 '.3',
 '.6',
 '.1',
 '.0',
 '.9',
 '.5',
 '.2',
 '.2',
 '.2',
 '.4',
 '.3',
 '.4',
 '.3',
 '.3',
 '.1',
 '.3',
 '.2',
 '.2',
 '.6',
 '.4',
 '.3',
 '.1',
 '.3',
 '.6',
 '.1',
 '.8',
 '.8',
 '.1',
 '.3',
 '.5',
 '.3',
 '.8',
 '.8',
 '.2',
 '.7',
 '.4',
 '.3',
 '.1',
 '.7',
 '.6',
 '.1',
 '.9',
 '.0',
 '.2',
 '.1',
 '.1',
 '.1',
 '.1',
 '.1',
 '.1',
 '.8',
 '.8',
 '.4',
 '.7',
 '.4',
 '.4',
 '.3',
 '.1',
 '.7',
 '.9',
 '.3',
 '.4',
 '.6',
 '.4',
 '.7',
 '.0',
 '.1',
 '.1',
 '.1',
 '.4',
 '.4',
 '.5',
 '.2',
 '.3',
 '.9',
 '.4',
 '.0',
 '.5',
 '.7',
 '.2',
 '.7',
 '.0',
 '.4',
 '.2',
 '.5',
 '.7',
 '.2',
 '.4',
 '.9',
 '.2',
 '.9',
 '.6',
 '.6',
 '.7',
 '.4',
 '.3',
 '.5',
 '.3',
 '.2',
 '.8',
 '.9',
 '.3',
 '.9',
 '.4',
 '.4',
 '.2',
 '.2',
 '.0',
 '.3',
 '.9',
 '.6',
 '.2',
 '.9',
 '.6',
 '.2',
 '.2',
 '.5',
 '.3',
 '.6',
 '.6',
 '.4',
 '.1',
 '.2',
 '.8',
 '.1',
 '.2',
 '.4',
 '.6',
 '.2',
 '.5',
 '.4',
 '.3',
 '.9',
 '.2',
 '.1',
 '.2',
 '.1',
 '.5',
 '.4',
 '.8',
 '.3',
 '.4',
 '.0',
 '.7',
 '.7',
 '.5',
 '.3',
 '.3',
 '.2',
 '.5',
 '.3',
 '.3',
 '.2',
 '.2',
 '.2',
 '.8',
 '.8',
 '.4',
 '.7',
 '.0',
 '.4',
 '.7',
 '.4',
 '.7',
 '.5',
 '.7',
 '.3',
 '.0',
 '.0',
 '.2',
 '.6',
 '.6',
 '.1',
 '.3',
 '.9',
 '.7',
 '.3',
 '.0',
 '.8',
 '.0',
 '.3',
 '.3',
 '.3',
 '.2',
 '.2',
 '.0',
 '.4',
 '.9',
 '.0',
 '.1',
 '.1',
 '.9',
 '.4',
 '.7',
 '.5',
 '.2',
 '.4',
 '.4',
 '.1',
 '.2',
 '.5',
 '.8',
 '.7',
 '.0',
 '.2',
 '.7',
 '.6',
 '.3',
 '.0',
 '.4',
 '.6',
 '.8',
 '.0',
 '.1',
 '.3',
 '.6',
 '.0',
 '.9',
 '.4',
 '.5',
 '.9',
 '.9',
 '.1',
 '.9',
 '.8',
 '.4',
 '.2',
 '.4',
 '.9',
 '.6',
 '.1',
 '.4',
 '.5',
 '.2',
 '.7',
 '.5',
 '.2',
 '.7',
 '.4',
 '.3',
 '.5',
 '.4',
 '.1',
 '.6',
 '.5',
 '.4',
 '.1',
 '.2',
 '.6',
 '.7',
 '.9',
 '.7',
 '.7',
 '.1',
 '.2',
 '.9',
 '.9',
 '.6',
 '.0',
 '.3',
 '.6',
 '.3',
 '.3',
 '.3',
 '.5',
 '.9',
 '.8',
 '.8',
 '.6',
 '.2',
 '.7',
 '.6',
 '.7',
 '.2',
 '.2',
 '.2',
 '.3',
 '.3',
 '.5',
 '.5',
 '.9',
 '.1',
 '.7',
 '.6',
 '.3',
 '.6',
 '.7',
 '.7',
 '.9',
 '.2',
 '.5',
 '.3',
 '.3',
 '.4',
 '.3',
 '.9',
 '.2',
 '.5',
 '.6',
 '.6',
 '.7',
 '.0',
 '.4',
 '.5',
 '.2',
 '.3',
 '.8',
 '.4',
 '.5',
 '.5',
 '.1',
 '.7',
 '.4',
 '.1',
 '.9',
 '.3',
 '.1',
 '.4',
 '.5',
 '.1',
 '.6',
 '.0',
 '.5',
 '.2',
 '.3',
 '.0',
 '.6',
 '.5',
 '.4',
 '.3',
 '.2',
 '.3',
 '.5',
 '.1',
 '.2',
 '.4',
 '.5',
 '.4',
 '.6',
 '.6',
 '.2',
 '.2',
 '.2',
 '.2',
 '.9',
 '.6',
 '.3',
 '.0',
 '.6',
 '.0',
 '.2',
 '.3',
 '.4',
 '.7',
 '.6',
 '.3',
 '.9',
 '.3',
 '.5',
 '.5',
 '.0',
 '.5',
 '.2',
 '.8',
 '.6',
 '.7',
 '.3',
 '.3',
 '.4',
 '.1',
 '.3',
 '.6',
 '.6',
 '.9',
 '.5',
 '.5',
 '.8',
 '.0',
 '.6',
 '.6',
 '.6',
 '.7',
 '.5',
 '.5',
 '.6',
 '.2',
 '.1',
 '.3',
 '.6',
 '.3',
 '.5',
 '.1',
 '.2',
 '.6',
 '.6',
 '.8',
 '.8',
 '.1',
 '.0',
 '.3',
 '.1',
 '.7',
 '.0',
 '.1',
 '.2',
 '.6',
 '.4',
 '.0',
 '.7',
 '.4',
 '.3',
 '.2',
 '.1',
 '.9',
 '.3',
 '.7',
 '.4',
 '.9',
 '.3',
 '.8',
 '.0',
 '.1',
 '.3',
 '.2',
 '.5',
 '.8',
 '.7',
 '.4',
 '.2',
 '.0',
 '.9',
 '.6',
 '.1',
 '.0',
 '.6',
 '.4',
 '.3',
 '.5',
 '.6',
 '.1',
 '.3',
 '.5',
 '.2',
 '.0',
 '.4',
 '.4',
 '.5',
 '.5',
 '.5',
 '.8',
 '.3',
 '.5',
 '.1',
 '.7',
 '.1',
 '.2',
 '.3',
 '.3',
 '.7',
 '.5',
 '.6',
 '.1',
 '.0',
 '.3',
 '.1',
 '.2',
 '.6',
 '.5',
 '.4',
 '.3',
 '.9',
 '.9',
 '.3',
 '.1',
 '.9',
 '.7',
 '.8',
 '.1',
 '.1',
 '.4',
 '.4',
 '.7',
 '.1',
 '.4',
 '.3',
 '.2',
 '.6',
 '.2',
 '.3',
 '.1',
 '.9',
 '.0',
 '.2',
 '.8',
 '.2',
 '.4',
 '.4',
 '.4',
 '.2',
 '.3',
 '.3',
 '.1',
 '.4',
 '.3',
 '.4',
 '.8',
 '.0',
 '.6',
 '.3',
 '.3',
 '.4',
 '.9',
 '.4',
 '.3',
 '.3',
 '.7',
 '.5',
 '.6',
 '.4',
 '.2',
 '.3',
 '.5',
 '.3',
 '.5',
 '.3',
 '.3',
 '.2',
 '.2',
 '.5',
 '.7',
 '.6',
 '.2',
 '.3',
 '.3',
 '.6',
 '.0',
 '.6',
 '.7',
 '.1',
 '.1',
 '.6',
 '.5',
 '.4',
 '.2',
 '.8',
 '.5',
 '.4',
 '.0',
 '.1',
 '.4',
 '.2',
 '.4',
 '.8',
 '.5',
 '.1',
 '.4',
 '.2',
 '.0',
 '.3',
 '.6',
 '.9',
 '.5',
 '.5',
 '.6',
 '.1',
 '.1',
 '.7',
 '.7',
 '.7',
 '.3',
 '.1',
 '.2',
 '.4',
 '.3',
 '.0',
 '.2',
 '.6',
 '.7',
 '.6',
 '.6',
 '.4',
 '.3',
 '.8',
 '.0',
 '.1',
 '.0',
 '.2',
 '.8',
 '.5',
 '.8',
 '.4',
 '.4',
 '.3',
 '.2',
 '.2',
 '.2',
 '.4',
 '.4',
 '.6',
 '.6',
 '.6',
 '.2',
 '.5',
 '.4',
 '.3',
 '.5',
 '.4',
 '.5',
 '.3',
 '.2',
 '.9',
 '.4',
 '.0',
 '.3',
 '.8',
 '.3',
 '.6',
 '.0',
 '.0',
 '.4',
 '.6',
 '.4',
 '.5',
 '.8',
 '.4',
 '.3',
 '.4',
 '.2',
 '.9',
 '.2',
 '.4',
 '.6',
 '.3',
 '.6',
 '.2',
 '.1',
 '.2',
 '.5',
 '.3',
 '.5',
 '.2',
 '.4',
 '.5',
 '.3',
 '.2',
 '.6',
 '.7',
 '.1',
 '.2',
 '.6',
 '.2',
 '.2',
 '.9',
 '.6',
 '.7',
 '.3',
 '.4',
 '.2',
 '.6',
 '.5',
 '.8',
 '.5',
 '.3',
 '.8',
 '.4',
 '.9',
 '.6',
 '.2',
 '.2',
 '.3',
 '.4',
 '.2',
 '.5',
 '.3',
 ...]

In [127]:
df['User-Rating']=l
df

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
0,Aankh Marey,"Kumar Sanu, Mika Singh, Neha Kakkar",BollywoodDance,Simmba,.8
1,Coca Cola,"Neha Kakkar, Tony Kakkar",BollywoodDanceRomantic,Luka Chuppi,.0
2,Apna Time Aayega,Ranveer Singh,BollywoodDance,Gully Boy,.7
3,Mungda,"Jyotica Tangri, Shaan, Subhro Ganguly",BollywoodDance,Total Dhamaal,.1
4,Tere Bin,"Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi",BollywoodRomantic,Simmba,.2
...,...,...,...,...,...
2415,Jana Tumhare Pyar Mein,Mukesh,BollywoodDance,Sasural,.2
2416,Tum Jaise Bigde Babu Se,Lata Mangeshkar,BollywoodDance,Jab Pyar Kisi Se Hota Hai,.2
2417,O Yaad Nahi Bhool Gaya,"Lata Mangeshkar, Suresh Wadkar",BollywoodDance,Lamhe,.5
2418,Ladi Re Ladi Tujhse Aankh Jo Ladi,Jagjit Kaur,BollywoodDance,Shola Aur Shabnam,.5
2419,Mummy Aur Daddy Mein Ladai Ho Gayi,Asha Bhosle,BollywoodDance,Shola Aur Shabnam,.6

In [128]:
df['Album/Movie']=df['Album/Movie'].str.replace(' ','')
df['Singer/Artists']=df['Singer/Artists'].str.replace(' ' ,'')
df

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
0,Aankh Marey,"KumarSanu,MikaSingh,NehaKakkar",BollywoodDance,Simmba,.8
1,Coca Cola,"NehaKakkar,TonyKakkar",BollywoodDanceRomantic,LukaChuppi,.0
2,Apna Time Aayega,RanveerSingh,BollywoodDance,GullyBoy,.7
3,Mungda,"JyoticaTangri,Shaan,SubhroGanguly",BollywoodDance,TotalDhamaal,.1
4,Tere Bin,"AseesKaur,RahatFatehAliKhan,TanishkBagchi",BollywoodRomantic,Simmba,.2
...,...,...,...,...,...
2415,Jana Tumhare Pyar Mein,Mukesh,BollywoodDance,Sasural,.2
2416,Tum Jaise Bigde Babu Se,LataMangeshkar,BollywoodDance,JabPyarKisiSeHotaHai,.2
2417,O Yaad Nahi Bhool Gaya,"LataMangeshkar,SureshWadkar",BollywoodDance,Lamhe,.5
2418,Ladi Re Ladi Tujhse Aankh Jo Ladi,JagjitKaur,BollywoodDance,SholaAurShabnam,.5
2419,Mummy Aur Daddy Mein Ladai Ho Gayi,AshaBhosle,BollywoodDance,SholaAurShabnam,.6

In [129]:
df['Singer/Artists']=df['Singer/Artists'].str.replace(' ' ,'')
df

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
0,Aankh Marey,"KumarSanu,MikaSingh,NehaKakkar",BollywoodDance,Simmba,.8
1,Coca Cola,"NehaKakkar,TonyKakkar",BollywoodDanceRomantic,LukaChuppi,.0
2,Apna Time Aayega,RanveerSingh,BollywoodDance,GullyBoy,.7
3,Mungda,"JyoticaTangri,Shaan,SubhroGanguly",BollywoodDance,TotalDhamaal,.1
4,Tere Bin,"AseesKaur,RahatFatehAliKhan,TanishkBagchi",BollywoodRomantic,Simmba,.2
...,...,...,...,...,...
2415,Jana Tumhare Pyar Mein,Mukesh,BollywoodDance,Sasural,.2
2416,Tum Jaise Bigde Babu Se,LataMangeshkar,BollywoodDance,JabPyarKisiSeHotaHai,.2
2417,O Yaad Nahi Bhool Gaya,"LataMangeshkar,SureshWadkar",BollywoodDance,Lamhe,.5
2418,Ladi Re Ladi Tujhse Aankh Jo Ladi,JagjitKaur,BollywoodDance,SholaAurShabnam,.5
2419,Mummy Aur Daddy Mein Ladai Ho Gayi,AshaBhosle,BollywoodDance,SholaAurShabnam,.6

In [130]:
df['tags']=df['Singer/Artists']+df['Genre']+df['Album/Movie']+df['User-Rating']
df['tags'][0]

'KumarSanu,MikaSingh,NehaKakkarBollywoodDanceSimmba.8'

In [131]:
new_df=df[['Song-Name','tags']]

In [132]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())
new_df

/var/folders/v5/fjnm3p1j2fxdgwf06wqbgyf00000gn/T/ipykernel_42817/2565169282.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

,Song-Name,tags
0,Aankh Marey,"kumarsanu,mikasingh,nehakakkarbollywooddancesi..."
1,Coca Cola,"nehakakkar,tonykakkarbollywooddanceromanticluk..."
2,Apna Time Aayega,ranveersinghbollywooddancegullyboy.7
3,Mungda,"jyoticatangri,shaan,subhrogangulybollywooddanc..."
4,Tere Bin,"aseeskaur,rahatfatehalikhan,tanishkbagchibolly..."
...,...,...
2415,Jana Tumhare Pyar Mein,mukeshbollywooddancesasural.2
2416,Tum Jaise Bigde Babu Se,latamangeshkarbollywooddancejabpyarkisisehotah...
2417,O Yaad Nahi Bhool Gaya,"latamangeshkar,sureshwadkarbollywooddancelamhe.5"
2418,Ladi Re Ladi Tujhse Aankh Jo Ladi,jagjitkaurbollywooddancesholaaurshabnam.5
2419,Mummy Aur Daddy Mein Ladai Ho Gayi,ashabhoslebollywooddancesholaaurshabnam.6

In [133]:
 pip install scikit-learn

Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [134]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2000)

In [135]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [136]:
vectors.shape

(2391, 2000)

In [137]:
cv.get_feature_names_out()

array(['55', '7ekterasaath', '9211', ...,
       'zubeengargbollywooddanceaashayein',
       'zubeengargbollywooddancedummaarodum',
       'zubeengargbollywooddanceiseeyou'], shape=(2000,), dtype=object)

In [154]:
#from sklearn.metrics.pairwise import cosine_similarity
#similarity = cosine_similarity(vectors)

In [155]:
#sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])'''

In [156]:
#new_df.rename(columns={'Song-Name':'title'},inplace=True)

In [157]:
#def recommend(music):
  #music_index = new_df[new_df['title']==music].index[0]
  #distances = similarity[music_index]
  #music_list = sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[1:6]
  #for i in music_list:
    #print(new_df.iloc[i[0]].title)

In [158]:
#recommend('Ishq Risk')

In [159]:
#df.head(50)

In [ ]:
#similarity = ...
#music_dict = ...

In [ ]:
#pickle.dump(new_df, open('/Users/test/Desktop/Task2/similarities.pkl','wb'))
#import pickle

#pickle.dump(similarity, open('similarities.pkl','wb'))
#pickle.dump(music_dict, open('musicrec.pkl','wb'))

In [164]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle

df = pd.read_csv("/Users/test/Downloads/ex.csv")

df['Singer/Artists'] = df['Singer/Artists'].fillna('')
df['Genre'] = df['Genre'].fillna('')
df['Album/Movie'] = df['Album/Movie'].fillna('')

df['tags'] = (
    df['Singer/Artists'] + " " +
    df['Genre'] + " " +
    df['Album/Movie']
)

df['tags'] = df['tags'].astype(str).str.lower()

new_df = df[['Song-Name', 'tags']].copy()
new_df.rename(columns={'Song-Name': 'title'}, inplace=True)

cv = CountVectorizer(max_features=2000, stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray()

similarity = cosine_similarity(vectors)

pickle.dump(new_df, open('musicrec.pkl','wb'))
pickle.dump(similarity, open('similarities.pkl','wb'))

print("✅ Pickle files recreated successfully!")

✅ Pickle files recreated successfully!

In [161]:
#pip install streamlit